### ISSUE TITLE
Deprecate better-npm-run in favor of this tool 

### ISSUE THREAD

**Issue by benoror** [kentcdodds/argv-set-env#1]
Kent, would you agree that `argv-set-env`'s approach is more elegant and less verbose than [benoror/better-npm-run](https://github.com/benoror/better-npm-run)?

I am thinking about updating the README with a message to hint users towards better alternative.

Cheers!

**Comment by kentcdodds** [comment]
It definitely solves my problem. But I could see scenarios where someone doesn't have a config file they can use to do the `require('argv-set-env')()` call and so they need to set it some other way. If I could get `cross-env` working then I think that would be a good solution. I think that it's close. But I probably wont give it time now that my issues have been resolved with this...

**Comment by benoror** [comment]
ok, it sounds reasonable. I will close this until there is something new.
